#!/usr/bin/env bash
# (c) 2019-2026 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

check_valid() {
	if [[ ${1} != *.ebuild ]]; then
		echo "Incorrect filename: ${1}"
		exit 1
	fi

	filename=${1##*/}
	version=$(patom -F '%{fullver}' "=category/${1%.ebuild}")
	if [[ -z ${version} ]]; then
		echo "Incorrect filename: ${1}"
		exit 1
	fi
}

if [[ ${#} -ne 2 ]]; then
	echo "Usage: pkgbump <from> <to>" >&2
	exit 1
fi

from=${1}
to=${2}

check_valid "${from}"
check_valid "${to}"

set -e -x

scriptdir=${BASH_SOURCE%/*}
cp "${from}" "${to}"
"${scriptdir}"/copybump "${to}"
ekeyword ~all "${to}"
if grep -q "^PYTHON_COMPAT" "${to}" && type -P gpy-impl &>/dev/null; then
	gpy-impl "${to}" -@dead || :
fi
# tell ebuilds we don't want everything
export PKGBUMPING=${version}
GENTOO_MIRRORS= ebuild "${to}" manifest
[[ ! -f Manifest ]] || git add Manifest
git add "${to}"
echo "${version}" > .pkgbump-pv
exec "${scriptdir}"/pkgdiff-mg "${from}" "${to}"
