#!/bin/sh
# fetch cache for rdep
# (c) 2020-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

set -e -x

mkdir -p "${TMPDIR:-/tmp}"/mgorny-dev-scripts
cd "${TMPDIR:-/tmp}"/mgorny-dev-scripts

wget -O rdeps.tar.xz https://qa-reports.gentoo.org/output/genrdeps/rdeps.tar.xz
xz -df rdeps.tar.xz

if command -v lz4 >/dev/null; then
	echo "lz4 available, repacking as rdeps.tar.lz4" >&2
	lz4 -f --rm rdeps.tar
else
	echo "fetched to rdeps.tar (install lz4 to compress)" >&2
fi
